const STYLE = `
.info{display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;border:1px solid #587187;border-radius:50%;font-size:10px;color:#a9c4d9;cursor:help;vertical-align:1px;margin-left:4px;touch-action:manipulation;user-select:none}.trendHead{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;flex-wrap:wrap}.rangeBtns{display:flex;gap:6px}.rangeBtn{background:#0b1722;border:1px solid #2c455a;color:#b9ccda;border-radius:999px;padding:6px 11px;font-size:12px;cursor:pointer}.rangeBtn.active{background:#18324a;color:#fff;border-color:#5f87a7}.chartGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.chartBox{position:relative;min-height:280px}.moneyChart{width:100%;height:280px;display:block;overflow:visible}.chartTip{position:absolute;display:none;pointer-events:none;background:#06111a;border:1px solid #38536a;border-radius:9px;padding:8px 10px;font-size:12px;line-height:1.45;box-shadow:0 8px 28px rgba(0,0,0,.35);z-index:3;min-width:170px}.legend{display:flex;gap:14px;flex-wrap:wrap;font-size:12px;color:#a9bdcc;margin:6px 0 2px}.legend span:before{content:'';display:inline-block;width:15px;height:3px;border-radius:3px;margin-right:6px;vertical-align:3px;background:var(--c)}.sourceNote{font-size:12px;color:#8da2b3;margin-top:10px}.glossary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.glossary>div{padding:10px 12px;border:1px solid #1d3142;border-radius:10px;background:#08141e;font-size:12px;color:#a9bdcc}.glossary b{color:#e4edf4}.infoPopover{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);width:min(92vw,520px);display:none;background:#08141e;border:1px solid #41647e;border-radius:12px;padding:12px 38px 12px 14px;color:#e7eff5;font-size:13px;line-height:1.5;box-shadow:0 12px 38px rgba(0,0,0,.45);z-index:1000}.infoPopover.show{display:block}.infoPopoverClose{position:absolute;right:8px;top:7px;border:0;background:transparent;color:#a9bdcc;font-size:20px;line-height:1;cursor:pointer;padding:4px 8px}@media(max-width:900px){.chartGrid{grid-template-columns:1fr}.glossary{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.glossary{grid-template-columns:1fr}.moneyChart{height:240px}.chartBox{min-height:240px}}
`;

const SECTION = `<section id="moneyTrend" class="section">
<div class="trendHead"><div><h2>Global Money Trend <span class="info" title="Mjesečna povijest dolazi iz istog promoviranog Global Money V2 source-of-trutha kao aktivni Core. Vercel chart čita live /api/history.">i</span></h2><p class="muted">Prati dvije stvari odvojeno: stvarni YoY rast broad moneyja i njegov povijesno normalizirani GMLI score.</p></div><div class="rangeBtns"><button class="rangeBtn" data-money-range="3Y">3Y</button><button class="rangeBtn active" data-money-range="5Y">5Y</button><button class="rangeBtn" data-money-range="MAX">MAX</button></div></div>
<div class="chartGrid">
<article class="card"><div class="tag">YoY broad-money growth <span class="info" title="USD-translated uključuje devizne tečajeve pri pretvaranju regionalnog novca u USD. FX-neutral pokazuje underlying monetarnu ekspanziju bez tog translation efekta.">i</span></div><div class="legend"><span style="--c:#64b5f6">USD-translated</span><span style="--c:#81c784">FX-neutral</span></div><div class="chartBox"><svg class="moneyChart" id="moneyYoyChart" viewBox="0 0 920 280" preserveAspectRatio="none"></svg><div class="chartTip" id="moneyYoyTip"></div></div><div class="sourceNote">0% = nema YoY rasta. Viši i ubrzavajući rast je likvidnosno povoljniji, ali nije sam po sebi trading signal.</div></article>
<article class="card"><div class="tag">GMLI Money score <span class="info" title="Score pretvara Money signal u povijesni z-score okvir. 50 je približno neutralno. Score nije postotak rasta niti očekivani prinos asseta.">i</span></div><div class="legend"><span style="--c:#64b5f6">USD score</span><span style="--c:#81c784">FX-neutral score</span></div><div class="chartBox"><svg class="moneyChart" id="moneyScoreChart" viewBox="0 0 920 280" preserveAspectRatio="none"></svg><div class="chartTip" id="moneyScoreTip"></div></div><div class="sourceNote">Referentne linije: 25/40/60/75. Zone su Strong Risk-Off / Risk-Off / Neutral / Risk-On / Strong Risk-On.</div></article>
</div>
<div class="glossary"><div><b>USD-translated</b> <span class="info" title="Regionalni broad money pretvoren u USD; USD kretanje može pojačati ili prigušiti signal.">i</span><br>Globalni money kako ga vidi USD investitor.</div><div><b>FX-neutral</b> <span class="info" title="Neutralizira FX translation prema frozen V2 metodologiji.">i</span><br>Čišći pogled na underlying monetarnu ekspanziju.</div><div><b>Funding</b> <span class="info" title="Funding je overlay convictiona. Supportive/neutral/restrictive ne smije sam prepisati Money Core.">i</span><br>Uvjeti financiranja; modifier convictiona, ne Core.</div><div><b>Conviction</b> <span class="info" title="0-10 ocjena freshnessa i slaganja Moneyja, transmissiona, Fundinga i tržišta. Nije očekivani return.">i</span><br>Koliko vjerujemo režimskoj interpretaciji.</div></div>
</section>`;

let historyRows=[];
let range='5Y';

function rowsForRange(){
  if(range==='MAX') return historyRows;
  return historyRows.slice(-(range==='3Y'?36:60));
}
function fmtMonth(s){const [y,m]=String(s).split('-');return new Date(Date.UTC(+y,+m-1,1)).toLocaleDateString('hr-HR',{month:'short',year:'numeric',timeZone:'UTC'});}
function setRange(r){range=r;document.querySelectorAll('[data-money-range]').forEach(b=>b.classList.toggle('active',b.dataset.moneyRange===r));renderCharts();}
function draw(svgId,tipId,rows,series,kind){
  const svg=document.getElementById(svgId),tip=document.getElementById(tipId); if(!svg||!tip)return;
  if(!rows.length){svg.innerHTML='<text x="20" y="40" fill="#8295a6">Nema dovoljno podataka</text>';return;}
  const W=920,H=280,p={l:52,r:18,t:18,b:34},pw=W-p.l-p.r,ph=H-p.t-p.b,vals=[];
  rows.forEach(r=>series.forEach(s=>{if(Number.isFinite(r[s.key])) vals.push(r[s.key]);}));
  if(!vals.length){svg.innerHTML='<text x="20" y="40" fill="#8295a6">Nema dovoljno podataka</text>';return;}
  let mn=Math.min(...vals),mx=Math.max(...vals); if(kind==='score'){mn=Math.min(mn,25);mx=Math.max(mx,75);} else {mn=Math.min(mn,0);mx=Math.max(mx,0);}
  const pad=Math.max((mx-mn)*.1,kind==='score'?5:1); mn-=pad;mx+=pad;
  const x=i=>p.l+(rows.length===1?0:i/(rows.length-1)*pw), y=v=>p.t+(mx-v)/(mx-mn)*ph; let out='';
  for(let i=0;i<=4;i++){const v=mn+(mx-mn)*i/4,yy=y(v);out+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="#1e3547" stroke-width="1"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end" fill="#7890a2" font-size="11">${kind==='score'?v.toFixed(0):v.toFixed(1)+'%'}</text>`;}
  (kind==='score'?[25,40,60,75]:[0]).forEach(v=>{if(v>=mn&&v<=mx)out+=`<line x1="${p.l}" y1="${y(v)}" x2="${W-p.r}" y2="${y(v)}" stroke="#607789" stroke-width="1.2" stroke-dasharray="5 5"/>`;});
  [...new Set([0,Math.round((rows.length-1)*.25),Math.round((rows.length-1)*.5),Math.round((rows.length-1)*.75),rows.length-1])].forEach(i=>{out+=`<text x="${x(i)}" y="${H-9}" text-anchor="middle" fill="#7890a2" font-size="11">${fmtMonth(rows[i].month)}</text>`;});
  series.forEach(s=>{let d='',open=false;rows.forEach((r,i)=>{const v=r[s.key];if(Number.isFinite(v)){d+=(open?' L ':' M ')+x(i)+' '+y(v);open=true;}else open=false;});out+=`<path d="${d}" fill="none" stroke="${s.color}" stroke-width="2.4" vector-effect="non-scaling-stroke"/>`;});
  out+=`<line id="${svgId}Hover" x1="0" y1="${p.t}" x2="0" y2="${H-p.b}" stroke="#d7e5ef" stroke-width="1" opacity="0"/>`;
  series.forEach((s,j)=>out+=`<circle id="${svgId}Dot${j}" r="4" fill="${s.color}" stroke="#071018" stroke-width="2" opacity="0"/>`);
  out+=`<rect x="${p.l}" y="${p.t}" width="${pw}" height="${ph}" fill="transparent"/>`; svg.innerHTML=out;
  svg.onpointermove=e=>{const box=svg.getBoundingClientRect(),sx=(e.clientX-box.left)/box.width*W,idx=Math.max(0,Math.min(rows.length-1,Math.round((sx-p.l)/pw*(rows.length-1)))),r=rows[idx],xx=x(idx),line=document.getElementById(svgId+'Hover');line.setAttribute('x1',xx);line.setAttribute('x2',xx);line.setAttribute('opacity','.55');let html=`<b>${fmtMonth(r.month)}</b><br><span class="muted">available ${r.available_date||'n/a'}</span>`;series.forEach((s,j)=>{const v=r[s.key],dot=document.getElementById(svgId+'Dot'+j);if(Number.isFinite(v)){dot.setAttribute('cx',xx);dot.setAttribute('cy',y(v));dot.setAttribute('opacity','1');html+=`<br><span style="color:${s.color}">●</span> ${s.label}: <b>${kind==='score'?v.toFixed(1):((v>=0?'+':'')+v.toFixed(2)+'%')}</b>`;}else dot.setAttribute('opacity','0');});tip.innerHTML=html;tip.style.display='block';const px=e.clientX-box.left;tip.style.left=Math.min(Math.max(px+12,6),box.width-190)+'px';tip.style.top=Math.max(e.clientY-box.top-70,4)+'px';};
  svg.onpointerleave=()=>{tip.style.display='none';const line=document.getElementById(svgId+'Hover');if(line)line.setAttribute('opacity','0');series.forEach((s,j)=>{const d=document.getElementById(svgId+'Dot'+j);if(d)d.setAttribute('opacity','0');});};
}
function renderCharts(){const rows=rowsForRange();draw('moneyYoyChart','moneyYoyTip',rows,[{key:'usd_yoy_pct',label:'USD YoY',color:'#64b5f6'},{key:'fx_neutral_yoy_pct',label:'FX-neutral YoY',color:'#81c784'}],'yoy');draw('moneyScoreChart','moneyScoreTip',rows,[{key:'usd_score',label:'USD score',color:'#64b5f6'},{key:'fx_neutral_score',label:'FX-neutral score',color:'#81c784'}],'score');}
function installPopover(){
  if(document.getElementById('infoPopover')) return;
  document.body.insertAdjacentHTML('beforeend','<div id="infoPopover" class="infoPopover" role="status" aria-live="polite"><button id="infoPopoverClose" class="infoPopoverClose" aria-label="Zatvori">×</button><div id="infoPopoverText"></div></div>');
  const pop=document.getElementById('infoPopover'),text=document.getElementById('infoPopoverText');let timer=null;const hide=()=>{pop.classList.remove('show');if(timer)clearTimeout(timer);};const show=el=>{const msg=el.getAttribute('title');if(!msg)return;text.textContent=msg;pop.classList.add('show');if(timer)clearTimeout(timer);timer=setTimeout(hide,8000);};
  document.querySelectorAll('.info').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label','Više informacija');el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();show(el);});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show(el);}});});
  document.getElementById('infoPopoverClose').onclick=hide;document.addEventListener('keydown',e=>{if(e.key==='Escape')hide();});document.addEventListener('click',e=>{if(pop.classList.contains('show')&&!pop.contains(e.target)&&!e.target.closest?.('.info'))hide();});
}
async function init(){
  if(document.getElementById('moneyTrend')) return;
  const style=document.createElement('style');style.textContent=STYLE;document.head.appendChild(style);
  const market=document.getElementById('market'); if(!market) return; market.insertAdjacentHTML('beforebegin',SECTION);
  const nav=document.querySelector('.nav'); if(nav&&!nav.querySelector('a[href="#moneyTrend"]')){const a=document.createElement('a');a.href='#moneyTrend';a.textContent='MONEY TREND';nav.insertBefore(a,nav.children[1]||null);}
  const tags=document.querySelectorAll('#now .tag'); if(tags[0])tags[0].innerHTML='ENGINE FACT · Global Money · USD-translated <span class="info" title="Broad money iz sedam regija preveden u USD. Uključuje i FX translation efekt.">i</span>'; if(tags[1])tags[1].innerHTML='ENGINE FACT · Global Money · FX-neutral <span class="info" title="Underlying broad-money rast uz neutraliziranje FX translation efekta.">i</span>'; if(tags[2])tags[2].innerHTML='CURRENT INFERENCE <span class="info" title="Research interpretacija: Money Core + Funding + market confirmation. Ne mijenja frozen Money metodologiju.">i</span>'; if(tags[3])tags[3].innerHTML='CONVICTION <span class="info" title="0-10 kvaliteta i slaganje dokaza. Nije očekivani return niti probability forecast.">i</span>';
  const radarH=document.querySelector('#radar h2');if(radarH&&!radarH.querySelector('.info'))radarH.insertAdjacentHTML('beforeend',' <span class="info" title="RESEARCH overlay za rano prepoznavanje asimetrije i promjene trenda. Nije Core niti automatski trading signal.">i</span>');
  document.querySelectorAll('[data-money-range]').forEach(b=>b.onclick=()=>setRange(b.dataset.moneyRange));
  try{const [report,history]=await Promise.all([fetch('/api/report',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('report '+r.status);return r.json();}),fetch('/api/history',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('history '+r.status);return r.json();})]);const m=report?.regime?.engine_fact?.money;if(m){const usd=document.getElementById('usd'),usdRegime=document.getElementById('usdRegime'),fxn=document.getElementById('fxn'),fxnRegime=document.getElementById('fxnRegime');if(usd)usd.textContent=(m.usd_yoy_pct>=0?'+':'')+m.usd_yoy_pct.toFixed(2)+'% YoY';if(usdRegime)usdRegime.innerHTML='Score <b>'+m.usd_score.toFixed(1)+'</b> · '+m.usd_regime+' · '+m.available_date+'<br><span class="small muted">FX contribution ≈ '+(m.usd_yoy_pct-m.fx_neutral_yoy_pct>=0?'+':'')+(m.usd_yoy_pct-m.fx_neutral_yoy_pct).toFixed(2)+' pp</span>';if(fxn)fxn.textContent=(m.fx_neutral_yoy_pct>=0?'+':'')+m.fx_neutral_yoy_pct.toFixed(2)+'% YoY';if(fxnRegime)fxnRegime.innerHTML='Score <b>'+m.fx_neutral_score.toFixed(1)+'</b> · '+m.fx_neutral_regime+' · '+m.agreement+'<br><span class="small muted">Underlying global broad-money growth, FX-neutral</span>';}
  historyRows=history?.rows||[];renderCharts();}catch(e){const s=document.querySelector('#moneyTrend .sourceNote');if(s)s.textContent='Money history unavailable: '+e.message;}
  installPopover();
}

init();
