from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

LIB = r'''import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_REL = 'research/global-money-v2/latest/global_money_v2.csv';
const SOURCE = path.join(ROOT, SOURCE_REL);

function num(v) {
  if (v == null || v === '') return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

export function getMoneyHistory() {
  const text = fs.readFileSync(SOURCE, 'utf8').trim();
  const lines = text.split(/\r?\n/).filter(Boolean);
  if (lines.length < 2) throw new Error('Global Money v2 history is empty');
  const headers = lines[0].split(',');
  const rows = lines.slice(1).map(line => {
    const cols = line.split(',');
    const x = Object.fromEntries(headers.map((h, i) => [h, cols[i] ?? '']));
    return {
      month: x.month,
      available_date: x.available_date,
      usd_yoy_pct: num(x.gbm_usd_yoy_pct),
      fx_neutral_yoy_pct: num(x.gbm_fxn_yoy_pct),
      fx_effect_pp: num(x.fx_effect_pp),
      usd_score: num(x.usd_score),
      fx_neutral_score: num(x.fxn_score)
    };
  }).filter(x => x.month && x.available_date && x.usd_yoy_pct != null && x.fx_neutral_yoy_pct != null);
  if (!rows.length) throw new Error('Global Money v2 history has no valid rows');
  const latest = rows.at(-1);
  return {
    schema_version: 'gmli-money-history-v1.0',
    engine_version: 'GMLI_GLOBAL_MONEY_V2_PBOC_OFFICIAL',
    evidence_tier: 'CORE_HISTORY',
    frequency: 'monthly',
    source_of_truth: SOURCE_REL,
    source_note: 'Generated by the same promoted official-source Global Money V2 pipeline used by the active Money Core. No separate spreadsheet/database is required.',
    score_note: 'Score = normalized historical position of the Money signal. It is not a percentage return or forecast. Regime bands: 0-25 strong risk-off, 25-40 risk-off, 40-60 neutral, 60-75 risk-on, 75-100 strong risk-on.',
    yoy_note: 'YoY is annual growth in global broad money. USD-translated includes currency translation; FX-neutral is designed to isolate underlying local-currency money growth.',
    start_month: rows[0].month,
    latest_month: latest.month,
    latest_available_date: latest.available_date,
    rows
  };
}
'''

API = r'''import { getMoneyHistory } from '../lib/money-history.js';
import { FROZEN_STATE } from '../lib/state.js';

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Cache-Control', 'public, max-age=0, must-revalidate');
  try {
    const history = getMoneyHistory();
    const latest = history.rows.at(-1);
    const core = FROZEN_STATE.money;
    if (latest.available_date !== core.available_date) {
      throw new Error(`History/Core date mismatch: ${latest.available_date} vs ${core.available_date}`);
    }
    for (const [a, b, label] of [
      [latest.usd_yoy_pct, core.usd_yoy_pct, 'USD YoY'],
      [latest.fx_neutral_yoy_pct, core.fx_neutral_yoy_pct, 'FX-neutral YoY'],
      [latest.usd_score, core.usd_score, 'USD score'],
      [latest.fx_neutral_score, core.fxn_score, 'FX-neutral score']
    ]) {
      if (a == null || b == null || Math.abs(a - b) > 0.0002) throw new Error(`${label} history/Core mismatch`);
    }
    return res.status(200).json(history);
  } catch (e) {
    return res.status(500).json({ error: e.message, endpoint: '/api/history' });
  }
}
'''

CHART_STYLE = r'''<style>
.info{display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;border:1px solid #587187;border-radius:50%;font-size:10px;color:#a9c4d9;cursor:help;vertical-align:1px;margin-left:4px}.trendHead{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;flex-wrap:wrap}.rangeBtns{display:flex;gap:6px}.rangeBtn{background:#0b1722;border:1px solid #2c455a;color:#b9ccda;border-radius:999px;padding:6px 11px;font-size:12px;cursor:pointer}.rangeBtn.active{background:#18324a;color:#fff;border-color:#5f87a7}.chartGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.chartBox{position:relative;min-height:280px}.moneyChart{width:100%;height:280px;display:block;overflow:visible}.chartTip{position:absolute;display:none;pointer-events:none;background:#06111a;border:1px solid #38536a;border-radius:9px;padding:8px 10px;font-size:12px;line-height:1.45;box-shadow:0 8px 28px rgba(0,0,0,.35);z-index:3;min-width:165px}.legend{display:flex;gap:14px;flex-wrap:wrap;font-size:12px;color:#a9bdcc;margin:6px 0 2px}.legend span:before{content:'';display:inline-block;width:15px;height:3px;border-radius:3px;margin-right:6px;vertical-align:3px;background:var(--c)}.sourceNote{font-size:12px;color:#8da2b3;margin-top:10px}.glossary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.glossary>div{padding:10px 12px;border:1px solid #1d3142;border-radius:10px;background:#08141e;font-size:12px;color:#a9bdcc}.glossary b{color:#e4edf4}@media(max-width:900px){.chartGrid{grid-template-columns:1fr}.glossary{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.glossary{grid-template-columns:1fr}.moneyChart{height:240px}.chartBox{min-height:240px}}
</style>'''

TREND_SECTION = r'''<section id="moneyTrend" class="section">
<div class="trendHead"><div><h2>Global Money Trend <span class="info" title="Mjesečna povijest dolazi iz istog promoviranog Global Money V2 source-of-trutha kao aktivni Core. Chart se regenerira pri svakom Pages buildu.">i</span></h2><p class="muted">Prati dvije stvari odvojeno: stvarni YoY rast broad moneyja i njegov povijesno normalizirani GMLI score.</p></div><div class="rangeBtns"><button class="rangeBtn" data-money-range="3Y">3Y</button><button class="rangeBtn active" data-money-range="5Y">5Y</button><button class="rangeBtn" data-money-range="MAX">MAX</button></div></div>
<div class="chartGrid">
<article class="card"><div class="tag">YoY broad-money growth <span class="info" title="USD-translated uključuje promjenu deviznih tečajeva pri pretvaranju regionalnog novca u USD. FX-neutral nastoji pokazati underlying rast novčane mase bez tog translation efekta.">i</span></div><div class="legend"><span style="--c:#64b5f6">USD-translated</span><span style="--c:#81c784">FX-neutral</span></div><div class="chartBox"><svg class="moneyChart" id="moneyYoyChart" viewBox="0 0 920 280" preserveAspectRatio="none"></svg><div class="chartTip" id="moneyYoyTip"></div></div><div class="sourceNote">0% linija = nema YoY rasta. Viši i ubrzavajući rast je likvidnosno povoljniji, ali nije sam po sebi trading signal.</div></article>
<article class="card"><div class="tag">GMLI Money score <span class="info" title="Score pretvara Money signal u povijesni z-score okvir. 50 je približno povijesno neutralno. Score nije postotak rasta niti očekivani prinos asseta.">i</span></div><div class="legend"><span style="--c:#64b5f6">USD score</span><span style="--c:#81c784">FX-neutral score</span></div><div class="chartBox"><svg class="moneyChart" id="moneyScoreChart" viewBox="0 0 920 280" preserveAspectRatio="none"></svg><div class="chartTip" id="moneyScoreTip"></div></div><div class="sourceNote">Referentne linije 40/60 odvajaju Risk-Off / Neutral / Risk-On zone; 25/75 su jače ekstremne zone.</div></article>
</div>
<div class="glossary"><div><b>USD-translated</b> <span class="info" title="Regionalni broad money pretvoren u USD; zato USD kretanje može pojačati ili prigušiti signal.">i</span><br>Globalni money kako ga vidi USD investitor.</div><div><b>FX-neutral</b> <span class="info" title="Neutralizira FX translation koliko metodologija dopušta; korisnije za underlying monetarnu ekspanziju.">i</span><br>Čišći pogled na monetarnu ekspanziju.</div><div><b>Funding</b> <span class="info" title="Funding je overlay convictiona. Supportive/neutral/restrictive ne smije sam prepisati Money Core.">i</span><br>Uvjeti financiranja; modifier convictiona, ne Core.</div><div><b>Conviction</b> <span class="info" title="0-10 ocjena kvalitete i slaganja dokaza: freshness, USD/FXN agreement, transmission, Funding i market confirmation. Nije očekivani return.">i</span><br>Koliko vjerujemo režimskoj interpretaciji, ne koliko će tržište narasti.</div></div>
</section>'''

CHART_JS = r'''
let gmliMoneyHistory=[];let gmliMoneyRange='5Y';
function moneyRangeRows(){if(!gmliMoneyHistory.length)return[];if(gmliMoneyRange==='MAX')return gmliMoneyHistory;const n=gmliMoneyRange==='3Y'?36:60;return gmliMoneyHistory.slice(-n)}
function setMoneyRange(r){gmliMoneyRange=r;document.querySelectorAll('[data-money-range]').forEach(b=>b.classList.toggle('active',b.dataset.moneyRange===r));renderMoneyCharts()}
function fmtMonth(s){const [y,m]=s.split('-');return new Date(Date.UTC(+y,+m-1,1)).toLocaleDateString('hr-HR',{month:'short',year:'numeric',timeZone:'UTC'})}
function drawMoneyChart(svgId,tipId,rows,series,kind){const svg=document.getElementById(svgId),tip=document.getElementById(tipId);if(!svg||!tip||!rows.length)return;const W=920,H=280,p={l:52,r:18,t:18,b:34},pw=W-p.l-p.r,ph=H-p.t-p.b;const vals=[];rows.forEach(r=>series.forEach(s=>{if(Number.isFinite(r[s.key]))vals.push(r[s.key])}));if(!vals.length){svg.innerHTML='<text x="20" y="40" fill="#8295a6">Nema dovoljno podataka</text>';return}let mn=Math.min(...vals),mx=Math.max(...vals);if(kind==='score'){mn=Math.min(mn,25);mx=Math.max(mx,75)}else{mn=Math.min(mn,0);mx=Math.max(mx,0)}const pad=Math.max((mx-mn)*.1,kind==='score'?5:1);mn-=pad;mx+=pad;const x=i=>p.l+(rows.length===1?0:i/(rows.length-1)*pw),y=v=>p.t+(mx-v)/(mx-mn)*ph;let out='';for(let i=0;i<=4;i++){const v=mn+(mx-mn)*i/4,yy=y(v);out+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="#1e3547" stroke-width="1"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end" fill="#7890a2" font-size="11">${kind==='score'?v.toFixed(0):v.toFixed(1)+'%'}</text>`}const refs=kind==='score'?[{v:25,t:'25'},{v:40,t:'40'},{v:60,t:'60'},{v:75,t:'75'}]:[{v:0,t:'0%'}];refs.forEach(q=>{if(q.v>=mn&&q.v<=mx)out+=`<line x1="${p.l}" y1="${y(q.v)}" x2="${W-p.r}" y2="${y(q.v)}" stroke="#607789" stroke-width="1.2" stroke-dasharray="5 5"/>`});const labelIdx=[0,Math.round((rows.length-1)*.25),Math.round((rows.length-1)*.5),Math.round((rows.length-1)*.75),rows.length-1];[...new Set(labelIdx)].forEach(i=>{out+=`<text x="${x(i)}" y="${H-9}" text-anchor="middle" fill="#7890a2" font-size="11">${fmtMonth(rows[i].month)}</text>`});series.forEach(s=>{let d='',open=false;rows.forEach((r,i)=>{const v=r[s.key];if(Number.isFinite(v)){d+=(open?' L ':' M ')+x(i)+' '+y(v);open=true}else open=false});out+=`<path d="${d}" fill="none" stroke="${s.color}" stroke-width="2.4" vector-effect="non-scaling-stroke"/>`});out+=`<line id="${svgId}Hover" x1="0" y1="${p.t}" x2="0" y2="${H-p.b}" stroke="#d7e5ef" stroke-width="1" opacity="0"/>`;series.forEach((s,j)=>out+=`<circle id="${svgId}Dot${j}" r="4" fill="${s.color}" stroke="#071018" stroke-width="2" opacity="0"/>`);out+=`<rect x="${p.l}" y="${p.t}" width="${pw}" height="${ph}" fill="transparent"/>`;svg.innerHTML=out;svg.onpointermove=e=>{const box=svg.getBoundingClientRect(),sx=(e.clientX-box.left)/box.width*W,idx=Math.max(0,Math.min(rows.length-1,Math.round((sx-p.l)/pw*(rows.length-1)))),r=rows[idx],xx=x(idx);const line=document.getElementById(svgId+'Hover');line.setAttribute('x1',xx);line.setAttribute('x2',xx);line.setAttribute('opacity','0.55');let html=`<b>${fmtMonth(r.month)}</b><br><span class="muted">available ${r.available_date}</span>`;series.forEach((s,j)=>{const v=r[s.key],dot=document.getElementById(svgId+'Dot'+j);if(Number.isFinite(v)){dot.setAttribute('cx',xx);dot.setAttribute('cy',y(v));dot.setAttribute('opacity','1');html+=`<br><span style="color:${s.color}">●</span> ${s.label}: <b>${kind==='score'?v.toFixed(1):((v>=0?'+':'')+v.toFixed(2)+'%')}</b>`}else dot.setAttribute('opacity','0')});tip.innerHTML=html;tip.style.display='block';const px=(e.clientX-box.left);tip.style.left=Math.min(Math.max(px+12,6),box.width-185)+'px';tip.style.top=Math.max((e.clientY-box.top)-70,4)+'px'};svg.onpointerleave=()=>{tip.style.display='none';const line=document.getElementById(svgId+'Hover');if(line)line.setAttribute('opacity','0');series.forEach((s,j)=>{const d=document.getElementById(svgId+'Dot'+j);if(d)d.setAttribute('opacity','0')})}}
function renderMoneyCharts(){const rows=moneyRangeRows();drawMoneyChart('moneyYoyChart','moneyYoyTip',rows,[{key:'usd_yoy_pct',label:'USD YoY',color:'#64b5f6'},{key:'fx_neutral_yoy_pct',label:'FX-neutral YoY',color:'#81c784'}],'yoy');drawMoneyChart('moneyScoreChart','moneyScoreTip',rows,[{key:'usd_score',label:'USD score',color:'#64b5f6'},{key:'fx_neutral_score',label:'FX-neutral score',color:'#81c784'}],'score')}
function initMoneyCharts(h){gmliMoneyHistory=h?.rows||[];document.querySelectorAll('[data-money-range]').forEach(b=>b.onclick=()=>setMoneyRange(b.dataset.moneyRange));renderMoneyCharts()}
'''

def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'missing marker: {label}')
    return text.replace(old, new, 1)

# New history contract files.
(ROOT / 'lib/money-history.js').write_text(LIB, encoding='utf-8')
(ROOT / 'api/history.js').write_text(API, encoding='utf-8')

# Dashboard: integrate history charts and explainers in the canonical UI.
idx = (ROOT / 'index.html').read_text(encoding='utf-8')
idx = replace_once(idx, '</head>', CHART_STYLE + '\n</head>', 'head')
idx = replace_once(idx, '<nav class="nav"><a href="#now">REGIME</a>', '<nav class="nav"><a href="#now">REGIME</a><a href="#moneyTrend">MONEY TREND</a>', 'nav')
idx = replace_once(idx, '<div class="tag">ENGINE FACT · USD Money</div>', '<div class="tag">ENGINE FACT · Global Money · USD-translated <span class="info" title="Broad money iz sedam regija preveden u USD. Uključuje i FX translation efekt.">i</span></div>', 'usd label')
idx = replace_once(idx, '<div class="tag">ENGINE FACT · FX-neutral</div>', '<div class="tag">ENGINE FACT · Global Money · FX-neutral <span class="info" title="Pogled na underlying rast broad moneyja uz neutraliziranje FX translation efekta.">i</span></div>', 'fxn label')
idx = replace_once(idx, '<article class="card"><div class="tag">CURRENT INFERENCE</div>', '<article class="card"><div class="tag">CURRENT INFERENCE <span class="info" title="Aktualna research interpretacija: Money Core + Funding + market confirmation. Ne mijenja frozen Money metodologiju.">i</span></div>', 'inference tooltip')
idx = replace_once(idx, '<article class="card"><div class="tag">CONVICTION</div>', '<article class="card"><div class="tag">CONVICTION <span class="info" title="0-10 kvaliteta/slaganost dokaza. Nije očekivani prinos niti probability forecast.">i</span></div>', 'conviction tooltip')
idx = replace_once(idx, '</div></section>\n<section id="market"', '</div></section>\n' + TREND_SECTION + '\n<section id="market"', 'trend section')
idx = replace_once(idx, '<section id="radar" class="section"><h2>Contrarian Trend Radar</h2>', '<section id="radar" class="section"><h2>Contrarian Trend Radar <span class="info" title="RESEARCH overlay za rano prepoznavanje asimetrije i promjene trenda. Nije Core niti automatski trading signal.">i</span></h2>', 'radar tooltip')
idx = replace_once(idx, '<a href="/api/report">/api/report</a>', '<a href="/api/report">/api/report</a> · <a href="/api/history">/api/history</a>', 'history footer')
idx = replace_once(idx, 'function marketCards(cm){', CHART_JS + '\nfunction marketCards(cm){', 'chart js')
idx = replace_once(idx, "const [r,d]=await Promise.all([fetch('/api/report').then(x=>x.json()),fetch('/api/radar').then(x=>x.json())]);", "const [r,d,h]=await Promise.all([fetch('/api/report').then(x=>x.json()),fetch('/api/radar').then(x=>x.json()),fetch('/api/history').then(x=>x.json())]);", 'history fetch')
idx = replace_once(idx, "usd.textContent=m.usd_score.toFixed(1);usdRegime.textContent=m.usd_regime+' · '+m.available_date;fxn.textContent=m.fx_neutral_score.toFixed(1);fxnRegime.textContent=m.fx_neutral_regime+' · '+m.agreement;", "usd.textContent=(m.usd_yoy_pct>=0?'+':'')+m.usd_yoy_pct.toFixed(2)+'% YoY';usdRegime.innerHTML='Score <b>'+m.usd_score.toFixed(1)+'</b> · '+m.usd_regime+' · '+m.available_date+'<br><span class=\"small muted\">FX contribution ≈ '+(m.usd_yoy_pct-m.fx_neutral_yoy_pct>=0?'+':'')+(m.usd_yoy_pct-m.fx_neutral_yoy_pct).toFixed(2)+' pp</span>';fxn.textContent=(m.fx_neutral_yoy_pct>=0?'+':'')+m.fx_neutral_yoy_pct.toFixed(2)+'% YoY';fxnRegime.innerHTML='Score <b>'+m.fx_neutral_score.toFixed(1)+'</b> · '+m.fx_neutral_regime+' · '+m.agreement+'<br><span class=\"small muted\">Underlying global broad-money growth, FX-neutral</span>';", 'money display')
idx = replace_once(idx, "fresh.innerHTML=`<b>ENGINE FACT:</b> Core ${m.available_date} (${m.freshness}). <b>NOWCAST:</b>", "fresh.innerHTML=`<b>GLOBAL MONEY:</b> USD-translated ${(m.usd_yoy_pct>=0?'+':'')+m.usd_yoy_pct.toFixed(2)}% YoY · FX-neutral ${(m.fx_neutral_yoy_pct>=0?'+':'')+m.fx_neutral_yoy_pct.toFixed(2)}% YoY. <b>ENGINE FACT:</b> Core ${m.available_date} (${m.freshness}). <b>NOWCAST:</b>", 'headline growth')
idx = replace_once(idx, ";marketGrid.innerHTML=marketCards(cm);", ";initMoneyCharts(h);marketGrid.innerHTML=marketCards(cm);", 'chart init')
(ROOT / 'index.html').write_text(idx, encoding='utf-8')

# Pages build: freeze the same history contract next to report/radar and fail closed on drift.
bp = (ROOT / 'scripts/build-pages-snapshot.mjs').read_text(encoding='utf-8')
bp = replace_once(bp, 'const [report, radar] = await Promise.all([', 'const [report, radar, history] = await Promise.all([', 'builder promise')
bp = replace_once(bp, "    invoke('api/radar.js')\n  ]);", "    invoke('api/radar.js'),\n    invoke('api/history.js')\n  ]);", 'builder history invoke')
anchor = "  if (report?.regime?.engine_fact?.money?.available_date !== '2026-07-31') {\n    throw new Error(`Unexpected active Money date ${report?.regime?.engine_fact?.money?.available_date}`);\n  }\n"
check = anchor + "  const historyLatest = history?.rows?.at(-1);\n  const coreMoney = report?.regime?.engine_fact?.money;\n  if (!historyLatest || historyLatest.available_date !== coreMoney.available_date) throw new Error('Pages history/Core date mismatch');\n  for (const [a,b,label] of [[historyLatest.usd_yoy_pct,coreMoney.usd_yoy_pct,'USD YoY'],[historyLatest.fx_neutral_yoy_pct,coreMoney.fx_neutral_yoy_pct,'FXN YoY'],[historyLatest.usd_score,coreMoney.usd_score,'USD score'],[historyLatest.fx_neutral_score,coreMoney.fx_neutral_score,'FXN score']]) { if (Math.abs(a-b)>0.0002) throw new Error(`Pages ${label} history/Core mismatch`); }\n"
bp = replace_once(bp, anchor, check, 'builder history check')
bp = replace_once(bp, "  await fs.writeFile(path.join(API_OUT, 'radar.json'), JSON.stringify(radar, null, 2) + '\\n');", "  await fs.writeFile(path.join(API_OUT, 'radar.json'), JSON.stringify(radar, null, 2) + '\\n');\n  await fs.writeFile(path.join(API_OUT, 'history.json'), JSON.stringify(history, null, 2) + '\\n');", 'history write')
bp = replace_once(bp, ".replaceAll(\"fetch('/api/radar')\", \"fetch('./api/radar.json', {cache:'no-store'})\")", ".replaceAll(\"fetch('/api/radar')\", \"fetch('./api/radar.json', {cache:'no-store'})\")\n    .replaceAll(\"fetch('/api/history')\", \"fetch('./api/history.json', {cache:'no-store'})\")", 'history fetch transform')
bp = replace_once(bp, ".replaceAll('href=\"/api/radar\"', 'href=\"./api/radar.json\"')", ".replaceAll('href=\"/api/radar\"', 'href=\"./api/radar.json\"')\n    .replaceAll('href=\"/api/history\"', 'href=\"./api/history.json\"')", 'history link transform')
bp = replace_once(bp, "    radar_as_of: radar.as_of", "    radar_as_of: radar.as_of,\n    history_start_month: history.start_month,\n    history_latest_month: history.latest_month,\n    history_rows: history.rows.length", 'builder output')
(ROOT / 'scripts/build-pages-snapshot.mjs').write_text(bp, encoding='utf-8')

# Pages workflow must assert the history snapshot exists.
wf = (ROOT / '.github/workflows/gmli-pages.yml').read_text(encoding='utf-8')
wf = replace_once(wf, '          test -s .pages/api/radar.json\n', '          test -s .pages/api/radar.json\n          test -s .pages/api/history.json\n', 'pages history assertion')
(ROOT / '.github/workflows/gmli-pages.yml').write_text(wf, encoding='utf-8')

print('PASS_INSTALL_MONEY_HISTORY_UI')
